extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

env:
  node: true
  jest: true

rules:
  no-console: 0
